#include "flecs-3.2.0/flecs.h"
#include "components.h"
#include "Physics.h"
#include "imgui-master/imgui.h"
#include "imgui-master/imstb_textedit.h"
#include "imgui-master/backends/imgui_impl_opengl3.h"
//#include "imgui-master/backends/imgui_impl_glfw.h"
#include "imgui-master/imgui.h"
//#include "imgui_impl_opengl.h"
#include <cstring> // For memset
